# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da5054037528191ade0e6789142a4829fabbb360c24230a18595764a7e4270899925de2d1b47aa62af92c8d0337a0d1470aa98cd5a860088c339bd3e60b62a80

test:
  secret_key_base: 7188709d34ba4437b9dd96333da9b9e77091c2162836775be9083486e2deaee1d683472d4685d854de5a8dbdb72b3cbef7e09d4648c1a5fd64e4f1a707bb959c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
